<?php

/**
 * @file
 * updates.install file.
 */

/**
 * Revert.
 */
function updates_update_7003() {
  features_revert_module(array(
    'panel_front_page',
  ));
}

/**
 * Revert.
 */
function updates_update_7004() {
  features_revert_module(array(
    'config_site_variables',
    'panel_front_page',
    'panel_site_template',
  ));
}

/**
 * Enable.
 */
function updates_update_7005() {
  module_enable(array(
    'content_type_slider_quote',
    'content_type_t_short',
  ));
}
